name: Build Snoopy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bison build-essential cmake flex git libedit-dev \
          libllvm13 llvm-13-dev libclang-13-dev python3 zlib1g-dev libelf-dev libfl-dev \
          python3-setuptools liblzma-dev libdebuginfod-dev arping netperf iperf

    - name: Install BCC
      run: |
        git clone https://github.com/iovisor/bcc.git
        mkdir bcc/build; cd bcc/build
        cmake ..
        make
        sudo make install
        cmake -DPYTHON_CMD=python3 .. # build python3 binding
        pushd src/python/
        make
        sudo make install
        popd

    - name: Install specific gobpf version
      run: go get github.com/iovisor/gobpf@v0.2.0

    - name: Update go.mod
      run: go mod tidy

    - name: Build Snoopy
      run: go build -v -o snoopy

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snoopy
        path: snoopy
