name: Build Snoopy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install BCC
      run: |
        sudo apt-get update
        sudo apt-get install -y bcc-tools libbcc-examples linux-headers-$(uname -r)

    - name: Install specific gobpf version
      run: |
        go get github.com/iovisor/gobpf@v0.2.0
        go mod tidy

    - name: Build Snoopy
      run: go build -v -o snoopy

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: snoopy
        path: snoopy